import itertools

from scripts.ssc.models.TopoAE_ext.config_libraries.euler_configs.mnist import (
    wcpath_mnist_s838_1024,
    wcpath_mnist_s838_512, wcpath_mnist_s838_256, wcpath_mnist_s838_64, wcpath_mnist_s838_128)
from src.datasets.datasets import MNIST_offline
from src.evaluation.config import ConfigEval
from src.models.WitnessComplexAE.config import ConfigGrid_WCAE
from src.models.autoencoder.autoencoders import ConvAE_MNIST, ConvAE_MNIST_3D

mnist_s838_notopo = [
ConfigGrid_WCAE(
    learning_rate=[1/10,1/100, 1/1000],
    batch_size=[1024],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=wcpath_mnist_s838_1024)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False,
),
ConfigGrid_WCAE(
    learning_rate=[1/10, 1/100, 1/1000],
    batch_size=[512],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=wcpath_mnist_s838_512)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False,
),
ConfigGrid_WCAE(
    learning_rate=[1/10, 1/100, 1/1000],
    batch_size=[256],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=wcpath_mnist_s838_256)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False),
ConfigGrid_WCAE(
    learning_rate=[1/10, 1/100, 1/1000],
    batch_size=[256],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=wcpath_mnist_s838_256)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False),
ConfigGrid_WCAE(
    learning_rate=[1/10, 1/100, 1/1000],
    batch_size=[128],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=wcpath_mnist_s838_128)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False),
ConfigGrid_WCAE(
    learning_rate=[1/10, 1/100, 1/1000],
    batch_size=[64],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=wcpath_mnist_s838_64)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False)
]


mnist_s838_notopo_list = list(itertools.chain(*[config_grid.configs_from_grid() for config_grid in mnist_s838_notopo]))

mnist_s838_notopo_3d = [
ConfigGrid_WCAE(
    learning_rate=[1/10,1/100,1/1000],
    batch_size=[bs],
    n_epochs=[1000],
    weight_decay=[1e-6],
    early_stopping=[30],
    rec_loss_weight=[1],
    top_loss_weight=[0],
    match_edges=['push_active'],
    k=[1],
    r_max=[10],
    model_class=[ConvAE_MNIST_3D],
    model_kwargs=[dict()],
    dataset=[MNIST_offline()],
    sampling_kwargs=[dict(root_path='/cluster/home/schsimo/MT/AEs-VAEs-TDA')],
    eval=[ConfigEval(
        active=False,
        evaluate_on='test',
        eval_manifold=False,
        save_eval_latent=True,
        save_train_latent=False,
        online_visualization=False,
        k_min=5,
        k_max=45,
        k_step=5,
    )],
    uid=[''],
    toposig_kwargs=[dict()],
    method_args=dict(n_jobs=[1], normalize=[True], mu_push=[1], online_wc=[True],
                     wc_offline=[dict(path_to_data=path_to_data)]),
    experiment_dir='/cluster/scratch/schsimo/output/mnist_3d_notopo',
    seed=838,
    device='cuda',
    num_threads=2,
    verbose=False) for bs,path_to_data in [(64,wcpath_mnist_s838_64),(128,wcpath_mnist_s838_128),(256,wcpath_mnist_s838_256),(512,wcpath_mnist_s838_512),(1024,wcpath_mnist_s838_1024)]]
mnist_s838_notopo_3d_list = list(itertools.chain(*[config_grid.configs_from_grid() for config_grid in mnist_s838_notopo_3d]))